### ISSUE TITLE
Unresolved reference: text

### ISSUE THREAD

**Issue by sgmheyhey** [PacktPublishing/Hands-On-Microservices-with-Kotlin#1]
File: `ExampleService.kt`
```
@Value(value = "\${service.message.text}")
private lateinit var text: String
```

File: `application.yml`
```
spring:
  config:
    use-legacy-processing: true

---
spring:
  profiles: "development"
service:
  message:
    text: "hi"
```

It's not working with `Maven: org.springframework.boot:spring-boot:2.4.1`

EDITED:

It was an issue about how to use `---` for a new section of the properties.

```
spring:
  config:
    use-legacy-processing: true
  profiles: "development"

---
service:
  message:
    text: "hi"
```
or simply just
```
service:
  message:
    text: "hi"
```

Those are working.

References: 

https://docs.spring.io/spring-boot/docs/2.4.1/reference/html/spring-boot-features.html#boot-features-external-config-files-multi-document

https://docs.spring.io/spring-boot/docs/2.4.1/reference/html/howto.html#howto-change-configuration-depending-on-the-environment
